import { ArrowRight, Eye, EyeOff, LockKeyhole, Moon, Sun } from 'lucide-react'
import { useState } from 'react'
import { useAppStore } from '../store'
import { applyTheme, getTheme, type Theme } from '../theme'

export function LoginPage(){
 const {login,branding}=useAppStore();const[account,setAccount]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState('');const[submitting,setSubmitting]=useState(false);const[theme,setTheme]=useState<Theme>(getTheme)
 const toggle=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);applyTheme(next)}
 async function submit(event:React.FormEvent){event.preventDefault();setSubmitting(true);setError('');const result=await login(account,password);setError(result.ok?'':result.reason??'登录失败');setSubmitting(false)}
 return <main className="login-page"><button className="login-theme-toggle icon-button" type="button" onClick={toggle} aria-label="切换明暗主题">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><section className="login-brand-panel login-brand-panel--image" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.32),rgba(0,0,0,.02)),url(${branding.loginBackgroundUrl})`}}><div className="login-brand"><span className="brand__mark">G</span><span><strong>{branding.projectName}</strong><small>需求协作平台</small></span></div></section><section className="login-form-panel"><form className="login-card" onSubmit={submit}><header><span className="login-card__icon"><LockKeyhole size={20}/></span><h2>登录 {branding.projectName}</h2><p>使用管理员创建的成员名称进入系统。</p></header><div className="field"><label htmlFor="login-account">成员</label><input id="login-account" autoFocus value={account} onChange={(e)=>setAccount(e.target.value)} autoComplete="username" placeholder="成员昵称"/></div><div className="field"><label htmlFor="login-password">密码</label><div className="password-input"><input id="login-password" type={showPassword?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password" placeholder="输入密码"/><button type="button" aria-label={showPassword?'隐藏密码':'显示密码'} onClick={()=>setShowPassword((v)=>!v)}>{showPassword?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></div>{error&&<div className="login-error" role="alert">{error}</div>}<button className="button button--primary login-submit" type="submit" disabled={!account.trim()||!password||submitting}>{submitting?'正在登录…':'登录'}<ArrowRight size={16}/></button></form></section></main>
}
